# Generated by Django 4.0.3 on 2022-04-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='书名',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='关联的书目',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='性别',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='名字',
            new_name='name',
        ),
    ]
